export type Difficulty = "Easy" | "Medium" | "Hard";

export interface Problem {
  id: string;
  title: string;
  difficulty: Difficulty;
  link?: string;
}

export interface TopicSection {
  id: string;
  title: string;
  color: string;
  bg: string;
  border: string;
  problems: Problem[];
}

const LC = (slug: string) => `https://leetcode.com/problems/${slug}/`;
const GFG = (slug: string) => `https://www.geeksforgeeks.org/problems/${slug}/1`;

export const CODING_TOPICS: TopicSection[] = [
  {
    id: "arrays",
    title: "Arrays",
    color: "#7c3aed",
    bg: "rgba(124,58,237,0.07)",
    border: "rgba(124,58,237,0.18)",
    problems: [
      { id: "arr-1",  title: "Majority Element - I",                           difficulty: "Easy",   link: LC("majority-element") },
      { id: "arr-2",  title: "Leaders in an Array",                            difficulty: "Easy",   link: GFG("leaders-in-an-array-1587115620") },
      { id: "arr-3",  title: "Rearrange Array Elements by Sign",               difficulty: "Medium", link: LC("rearrange-array-elements-by-sign") },
      { id: "arr-4",  title: "Print the Matrix in Spiral Manner",              difficulty: "Medium", link: LC("spiral-matrix") },
      { id: "arr-5",  title: "Pascal's Triangle I",                            difficulty: "Easy",   link: LC("pascals-triangle") },
      { id: "arr-6",  title: "Pascal's Triangle II",                           difficulty: "Easy",   link: LC("pascals-triangle-ii") },
      { id: "arr-7",  title: "Pascal's Triangle III",                          difficulty: "Medium", link: GFG("pascal-triangle0652") },
      { id: "arr-8",  title: "Rotate Matrix by 90 Degrees",                   difficulty: "Medium", link: LC("rotate-image") },
      { id: "arr-9",  title: "Two Sum",                                        difficulty: "Easy",   link: LC("two-sum") },
      { id: "arr-10", title: "3 Sum",                                          difficulty: "Medium", link: LC("3sum") },
      { id: "arr-11", title: "4 Sum",                                          difficulty: "Hard",   link: LC("4sum") },
      { id: "arr-12", title: "Sort an Array of 0's 1's and 2's",              difficulty: "Easy",   link: LC("sort-colors") },
      { id: "arr-13", title: "Kadane's Algorithm",                             difficulty: "Medium", link: LC("maximum-subarray") },
      { id: "arr-14", title: "Next Permutation",                               difficulty: "Medium", link: LC("next-permutation") },
      { id: "arr-15", title: "Majority Element - II",                          difficulty: "Medium", link: LC("majority-element-ii") },
      { id: "arr-16", title: "Find the Repeating and Missing Number",          difficulty: "Hard",   link: GFG("find-missing-and-repeating2512") },
      { id: "arr-17", title: "Count Inversions",                               difficulty: "Hard",   link: GFG("inversion-of-array-1587115620") },
      { id: "arr-18", title: "Reverse Pairs",                                  difficulty: "Hard",   link: LC("reverse-pairs") },
      { id: "arr-19", title: "Maximum Product Subarray in an Array",           difficulty: "Medium", link: LC("maximum-product-subarray") },
      { id: "arr-20", title: "Merge Two Sorted Arrays without Extra Space",    difficulty: "Hard",   link: GFG("merge-two-sorted-arrays-1587115620") },
      { id: "arr-21", title: "Longest Consecutive Sequence in an Array",       difficulty: "Medium", link: LC("longest-consecutive-sequence") },
      { id: "arr-22", title: "Longest Subarray with Sum K",                   difficulty: "Medium", link: GFG("longest-sub-array-with-sum-k0809") },
      { id: "arr-23", title: "Count Subarrays with Given Sum",                difficulty: "Medium", link: LC("subarray-sum-equals-k") },
      { id: "arr-24", title: "Count Subarrays with Given XOR K",              difficulty: "Hard",   link: GFG("count-subarray-with-given-xor") },
    ],
  },
  {
    id: "binary-search",
    title: "Binary Search",
    color: "#0891b2",
    bg: "rgba(8,145,178,0.07)",
    border: "rgba(8,145,178,0.18)",
    problems: [
      { id: "bs-1",  title: "Binary Search",                              difficulty: "Easy",   link: LC("binary-search") },
      { id: "bs-2",  title: "Search X in Sorted Array",                  difficulty: "Easy",   link: LC("binary-search") },
      { id: "bs-3",  title: "Lower Bound",                               difficulty: "Easy",   link: GFG("floor-in-a-sorted-array-1587115620") },
      { id: "bs-4",  title: "Upper Bound",                               difficulty: "Easy",   link: GFG("ceil-the-floor") },
      { id: "bs-5",  title: "Search Insert Position",                    difficulty: "Easy",   link: LC("search-insert-position") },
      { id: "bs-6",  title: "Floor and Ceil in Sorted Array",            difficulty: "Easy",   link: GFG("ceil-the-floor") },
      { id: "bs-7",  title: "First and Last Occurrence",                 difficulty: "Easy",   link: LC("find-first-and-last-position-of-element-in-sorted-array") },
      { id: "bs-8",  title: "Search in Rotated Sorted Array - I",        difficulty: "Medium", link: LC("search-in-rotated-sorted-array") },
      { id: "bs-9",  title: "Search in Rotated Sorted Array - II",       difficulty: "Medium", link: LC("search-in-rotated-sorted-array-ii") },
      { id: "bs-10", title: "Find Minimum in Rotated Sorted Array",      difficulty: "Medium", link: LC("find-minimum-in-rotated-sorted-array") },
      { id: "bs-11", title: "Find Out How Many Times Array is Rotated",  difficulty: "Easy",   link: GFG("rotation4723") },
      { id: "bs-12", title: "Single Element in Sorted Array",            difficulty: "Medium", link: LC("single-element-in-a-sorted-array") },
      { id: "bs-13", title: "Find Square Root of a Number",              difficulty: "Easy",   link: LC("sqrtx") },
      { id: "bs-14", title: "Find Nth Root of a Number",                 difficulty: "Medium", link: GFG("find-nth-root-of-m5843") },
      { id: "bs-15", title: "Find the Smallest Divisor",                 difficulty: "Medium", link: LC("find-the-smallest-divisor-given-a-threshold") },
      { id: "bs-16", title: "Koko Eating Bananas",                       difficulty: "Medium", link: LC("koko-eating-bananas") },
      { id: "bs-17", title: "Minimum Days to Make M Bouquets",           difficulty: "Medium", link: LC("minimum-number-of-days-to-make-m-bouquets") },
      { id: "bs-18", title: "Aggressive Cows",                           difficulty: "Hard",   link: GFG("aggressive-cows") },
      { id: "bs-19", title: "Book Allocation Problem",                   difficulty: "Hard",   link: GFG("allocate-minimum-number-of-pages0937") },
      { id: "bs-20", title: "Find Peak Element",                         difficulty: "Medium", link: LC("find-peak-element") },
      { id: "bs-21", title: "Median of 2 Sorted Arrays",                 difficulty: "Hard",   link: LC("median-of-two-sorted-arrays") },
      { id: "bs-22", title: "Kth Element of 2 Sorted Arrays",            difficulty: "Hard",   link: GFG("k-th-element-of-two-sorted-array1317") },
      { id: "bs-23", title: "Minimize Max Distance to Gas Station",      difficulty: "Hard",   link: GFG("minimize-max-distance-to-gas-station") },
      { id: "bs-24", title: "Split Array - Largest Sum",                 difficulty: "Hard",   link: LC("split-array-largest-sum") },
      { id: "bs-25", title: "Find Row with Maximum 1's",                 difficulty: "Medium", link: GFG("row-with-max-1s0023") },
      { id: "bs-26", title: "Search in a 2D Matrix",                    difficulty: "Medium", link: LC("search-a-2d-matrix") },
      { id: "bs-27", title: "Search in 2D Matrix - II",                  difficulty: "Medium", link: LC("search-a-2d-matrix-ii") },
      { id: "bs-28", title: "Find Peak Element - II",                    difficulty: "Hard",   link: LC("find-a-peak-element-ii") },
      { id: "bs-29", title: "Matrix Median",                             difficulty: "Hard",   link: GFG("median-in-a-row-wise-sorted-matrix1527") },
    ],
  },
  {
    id: "recursion",
    title: "Recursion & Backtracking",
    color: "#059669",
    bg: "rgba(5,150,105,0.07)",
    border: "rgba(5,150,105,0.18)",
    problems: [
      { id: "rec-1",  title: "Pow(x, n)",                                   difficulty: "Medium", link: LC("powx-n") },
      { id: "rec-2",  title: "Generate Parentheses",                        difficulty: "Medium", link: LC("generate-parentheses") },
      { id: "rec-3",  title: "Power Set",                                   difficulty: "Medium", link: LC("subsets") },
      { id: "rec-4",  title: "Check if Subsequence with Sum K Exists",      difficulty: "Easy",   link: GFG("check-if-there-exists-a-subsequence-with-sum-k") },
      { id: "rec-5",  title: "Count All Subsequences with Sum K",           difficulty: "Medium", link: GFG("perfect-sum-problem5633") },
      { id: "rec-6",  title: "Combination Sum",                             difficulty: "Medium", link: LC("combination-sum") },
      { id: "rec-7",  title: "Combination Sum II",                          difficulty: "Medium", link: LC("combination-sum-ii") },
      { id: "rec-8",  title: "Subsets I",                                   difficulty: "Medium", link: LC("subsets") },
      { id: "rec-9",  title: "Subsets II",                                  difficulty: "Medium", link: LC("subsets-ii") },
      { id: "rec-10", title: "Combination Sum III",                         difficulty: "Medium", link: LC("combination-sum-iii") },
      { id: "rec-11", title: "Letter Combinations of a Phone Number",       difficulty: "Medium", link: LC("letter-combinations-of-a-phone-number") },
      { id: "rec-12", title: "Palindrome Partitioning",                     difficulty: "Hard",   link: LC("palindrome-partitioning") },
      { id: "rec-13", title: "Word Search",                                 difficulty: "Medium", link: LC("word-search") },
      { id: "rec-14", title: "N Queen",                                     difficulty: "Hard",   link: LC("n-queens") },
      { id: "rec-15", title: "Rat in a Maze",                               difficulty: "Medium", link: GFG("rat-in-a-maze-problem") },
      { id: "rec-16", title: "M Coloring Problem",                          difficulty: "Hard",   link: GFG("m-coloring-problem-1587115620") },
      { id: "rec-17", title: "Sudoku Solver",                               difficulty: "Hard",   link: LC("sudoku-solver") },
    ],
  },
  {
    id: "linked-list",
    title: "Singly Linked List",
    color: "#d97706",
    bg: "rgba(217,119,6,0.07)",
    border: "rgba(217,119,6,0.18)",
    problems: [
      { id: "ll-1",  title: "Introduction to Singly LinkedList",                  difficulty: "Easy",   link: GFG("introduction-to-linked-list") },
      { id: "ll-2",  title: "Traversal in Linked List",                           difficulty: "Easy",   link: GFG("linked-list-traversal") },
      { id: "ll-3",  title: "Deletion in Linked List",                            difficulty: "Easy",   link: GFG("delete-a-node-in-single-linked-list") },
      { id: "ll-4",  title: "Insertion in Linked List",                           difficulty: "Easy",   link: GFG("linked-list-insertion-1587115620") },
      { id: "ll-5",  title: "Deletion of the Head of LL",                         difficulty: "Easy",   link: GFG("delete-the-head-node-in-singly-linked-list") },
      { id: "ll-6",  title: "Deletion of the Tail of Linked List",                difficulty: "Easy",   link: GFG("delete-the-tail-node-in-singly-linked-list") },
      { id: "ll-7",  title: "Deletion of the Kth Element of Linked List",         difficulty: "Easy",   link: GFG("delete-node-in-singly-linked-list") },
      { id: "ll-8",  title: "Delete the Element with Value X",                    difficulty: "Easy",   link: GFG("delete-without-head-pointer") },
      { id: "ll-9",  title: "Insertion at the Head of Linked List",               difficulty: "Easy",   link: GFG("linked-list-insertion-1587115620") },
      { id: "ll-10", title: "Insertion at the Tail of Linked List",               difficulty: "Easy",   link: GFG("linked-list-insertion-1587115620") },
      { id: "ll-11", title: "Insertion at the Kth Position of Linked List",       difficulty: "Easy",   link: GFG("linked-list-insertion-1587115620") },
      { id: "ll-12", title: "Insertion Before the Value X in Linked List",        difficulty: "Easy",   link: GFG("insert-before-given-node-in-linked-list") },
      { id: "ll-13", title: "Add Two Numbers in Linked List",                     difficulty: "Medium", link: LC("add-two-numbers") },
      { id: "ll-14", title: "Segregate Odd and Even Nodes in Linked List",        difficulty: "Medium", link: GFG("segregate-even-and-odd-nodes-in-a-linked-list") },
      { id: "ll-15", title: "Sort a Linked List of 0's 1's and 2's",             difficulty: "Medium", link: GFG("given-a-linked-list-of-0s-1s-and-2s-sort-it") },
      { id: "ll-16", title: "Remove Nth Node from the Back of the LL",            difficulty: "Medium", link: LC("remove-nth-node-from-end-of-list") },
      { id: "ll-17", title: "Reverse a LL",                                       difficulty: "Easy",   link: LC("reverse-linked-list") },
      { id: "ll-18", title: "Add One to a Number Represented by Linked List",     difficulty: "Medium", link: GFG("add-1-to-a-number-represented-as-linked-list") },
      { id: "ll-19", title: "Find Middle of Linked List",                         difficulty: "Easy",   link: LC("middle-of-the-linked-list") },
      { id: "ll-20", title: "Delete the Middle Node in LL",                       difficulty: "Medium", link: LC("delete-the-middle-node-of-a-linked-list") },
      { id: "ll-21", title: "Check if LL is Palindrome or Not",                   difficulty: "Medium", link: LC("palindrome-linked-list") },
      { id: "ll-22", title: "Find the Intersection Point of Y LL",               difficulty: "Medium", link: LC("intersection-of-two-linked-lists") },
      { id: "ll-23", title: "Detect a Loop in Linked List",                       difficulty: "Easy",   link: LC("linked-list-cycle") },
      { id: "ll-24", title: "Find the Starting Point in LL",                      difficulty: "Medium", link: LC("linked-list-cycle-ii") },
      { id: "ll-25", title: "Length of Loop in LL",                               difficulty: "Medium", link: GFG("find-length-of-loop") },
      { id: "ll-26", title: "Reverse LL in Group of Given Size K",               difficulty: "Hard",   link: LC("reverse-nodes-in-k-group") },
      { id: "ll-27", title: "Rotate a Linked List",                               difficulty: "Medium", link: LC("rotate-list") },
      { id: "ll-28", title: "Merge Two Sorted Lists",                             difficulty: "Easy",   link: LC("merge-two-sorted-lists") },
      { id: "ll-29", title: "Flattening of LL",                                   difficulty: "Hard",   link: GFG("flattening-a-linked-list") },
      { id: "ll-30", title: "Sort LL",                                            difficulty: "Medium", link: LC("sort-list") },
      { id: "ll-31", title: "Clone a LL with Random and Next Pointer",            difficulty: "Hard",   link: LC("copy-list-with-random-pointer") },
    ],
  },
  {
    id: "doubly-linked-list",
    title: "Doubly Linked List",
    color: "#b45309",
    bg: "rgba(180,83,9,0.07)",
    border: "rgba(180,83,9,0.18)",
    problems: [
      { id: "dll-1",  title: "Deletion in Doubly LL",                              difficulty: "Easy",   link: GFG("delete-node-in-doubly-linked-list") },
      { id: "dll-2",  title: "Insertion in DLL",                                   difficulty: "Easy",   link: GFG("doubly-linked-list-insertion-at-given-position") },
      { id: "dll-3",  title: "Convert Array to Doubly Linked List",                difficulty: "Easy",   link: GFG("convert-array-to-doubly-linked-list") },
      { id: "dll-4",  title: "Delete Head of Doubly Linked List",                  difficulty: "Easy",   link: GFG("delete-head-of-doubly-linked-list") },
      { id: "dll-5",  title: "Delete Tail of Doubly Linked List",                  difficulty: "Easy",   link: GFG("delete-tail-of-doubly-linked-list") },
      { id: "dll-6",  title: "Delete Kth Element of Doubly Linked List",           difficulty: "Easy",   link: GFG("delete-kth-element-of-doubly-linked-list") },
      { id: "dll-7",  title: "Removing Given Node in Doubly Linked List",          difficulty: "Easy",   link: GFG("remove-given-node-in-doubly-linked-list") },
      { id: "dll-8",  title: "Insert Node Before Head in Doubly Linked List",      difficulty: "Easy",   link: GFG("insert-node-at-beginning-of-doubly-linked-list") },
      { id: "dll-9",  title: "Insert Node Before Tail in Doubly Linked List",      difficulty: "Easy",   link: GFG("insert-node-before-tail-in-doubly-linked-list") },
      { id: "dll-10", title: "Insert Node Before Kth Node in Doubly Linked List",  difficulty: "Easy",   link: GFG("insert-node-before-kth-position-in-doubly-linked-list") },
      { id: "dll-11", title: "Insert Before Given Node in Doubly Linked List",     difficulty: "Easy",   link: GFG("insert-before-given-node-in-doubly-linked-list") },
      { id: "dll-12", title: "Delete All Occurrences of a Key in DLL",            difficulty: "Medium", link: GFG("delete-all-occurrences-of-a-given-key-in-a-doubly-linked-list") },
      { id: "dll-13", title: "Remove Duplicates from Sorted DLL",                  difficulty: "Medium", link: GFG("remove-duplicates-from-a-sorted-doubly-linked-list") },
    ],
  },
  {
    id: "bit-manipulation",
    title: "Bit Manipulation",
    color: "#db2777",
    bg: "rgba(219,39,119,0.07)",
    border: "rgba(219,39,119,0.18)",
    problems: [
      { id: "bit-1", title: "Introduction to Bits and Tricks",                           difficulty: "Easy",   link: GFG("bit-manipulation-1666686020") },
      { id: "bit-2", title: "Minimum Bit Flips to Convert Number",                       difficulty: "Easy",   link: LC("minimum-bit-flips-to-convert-number") },
      { id: "bit-3", title: "Single Number - I",                                         difficulty: "Easy",   link: LC("single-number") },
      { id: "bit-4", title: "Single Number - II",                                        difficulty: "Medium", link: LC("single-number-ii") },
      { id: "bit-5", title: "Single Number - III",                                       difficulty: "Medium", link: LC("single-number-iii") },
      { id: "bit-6", title: "Divide Two Numbers without Multiplication and Division",    difficulty: "Medium", link: LC("divide-two-integers") },
      { id: "bit-7", title: "Power Set",                                                 difficulty: "Medium", link: LC("subsets") },
      { id: "bit-8", title: "XOR of Numbers in a Given Range",                          difficulty: "Medium", link: GFG("calculate-xor-from-1-to-n") },
    ],
  },
  {
    id: "greedy",
    title: "Greedy",
    color: "#16a34a",
    bg: "rgba(22,163,74,0.07)",
    border: "rgba(22,163,74,0.18)",
    problems: [
      { id: "gr-1",  title: "Assign Cookies",                                              difficulty: "Easy",   link: LC("assign-cookies") },
      { id: "gr-2",  title: "Lemonade Change",                                             difficulty: "Easy",   link: LC("lemonade-change") },
      { id: "gr-3",  title: "Jump Game - I",                                               difficulty: "Medium", link: LC("jump-game") },
      { id: "gr-4",  title: "Shortest Job First",                                          difficulty: "Medium", link: GFG("shortest-job-first") },
      { id: "gr-5",  title: "Job Sequencing Problem",                                      difficulty: "Medium", link: GFG("job-sequencing-problem-1587115620") },
      { id: "gr-6",  title: "N Meetings in One Room",                                      difficulty: "Medium", link: GFG("n-meetings-in-one-room-1587115620") },
      { id: "gr-7",  title: "Non-overlapping Intervals",                                   difficulty: "Medium", link: LC("non-overlapping-intervals") },
      { id: "gr-8",  title: "Insert Interval",                                             difficulty: "Medium", link: LC("insert-interval") },
      { id: "gr-9",  title: "Minimum Number of Platforms Required for a Railway",          difficulty: "Medium", link: GFG("minimum-platforms-1587115620") },
      { id: "gr-10", title: "Valid Parenthesis Checker",                                   difficulty: "Medium", link: LC("valid-parentheses") },
      { id: "gr-11", title: "Candy",                                                       difficulty: "Hard",   link: LC("candy") },
      { id: "gr-12", title: "Maximum Points You Can Obtain from Cards",                    difficulty: "Medium", link: LC("maximum-points-you-can-obtain-from-cards") },
    ],
  },
  {
    id: "sliding-window",
    title: "Sliding Window & Two Pointers",
    color: "#0369a1",
    bg: "rgba(3,105,161,0.07)",
    border: "rgba(3,105,161,0.18)",
    problems: [
      { id: "sw-1", title: "Longest Substring Without Repeating Characters",           difficulty: "Medium", link: LC("longest-substring-without-repeating-characters") },
      { id: "sw-2", title: "Max Consecutive Ones III",                                 difficulty: "Medium", link: LC("max-consecutive-ones-iii") },
      { id: "sw-3", title: "Fruit Into Baskets",                                       difficulty: "Medium", link: LC("fruit-into-baskets") },
      { id: "sw-4", title: "Longest Substring With At Most K Distinct Characters",     difficulty: "Medium", link: GFG("longest-k-unique-characters-substring0853") },
      { id: "sw-5", title: "Longest Repeating Character Replacement",                  difficulty: "Medium", link: LC("longest-repeating-character-replacement") },
      { id: "sw-6", title: "Minimum Window Substring",                                 difficulty: "Hard",   link: LC("minimum-window-substring") },
      { id: "sw-7", title: "Number of Substrings Containing All Three Characters",     difficulty: "Medium", link: LC("number-of-substrings-containing-all-three-characters") },
      { id: "sw-8", title: "Binary Subarrays With Sum",                                difficulty: "Medium", link: LC("binary-subarrays-with-sum") },
      { id: "sw-9", title: "Count Number of Nice Subarrays",                           difficulty: "Medium", link: LC("count-number-of-nice-subarrays") },
    ],
  },
  {
    id: "stack-queue",
    title: "Stack & Queue",
    color: "#c2410c",
    bg: "rgba(194,65,12,0.07)",
    border: "rgba(194,65,12,0.18)",
    problems: [
      { id: "sq-1",  title: "Implement Stack using Arrays",      difficulty: "Easy",   link: GFG("implement-stack-using-array") },
      { id: "sq-2",  title: "Implement Queue using Arrays",      difficulty: "Easy",   link: GFG("implement-queue-using-array") },
      { id: "sq-3",  title: "Implement Stack using Queue",       difficulty: "Easy",   link: LC("implement-stack-using-queues") },
      { id: "sq-4",  title: "Implement Queue using Stack",       difficulty: "Easy",   link: LC("implement-queue-using-stacks") },
      { id: "sq-5",  title: "Implement Stack using LinkedList",  difficulty: "Easy",   link: GFG("implement-stack-using-linked-list") },
      { id: "sq-6",  title: "Implement Queue using LinkedList",  difficulty: "Easy",   link: GFG("implement-queue-using-linked-list") },
      { id: "sq-7",  title: "Balanced Parenthesis",              difficulty: "Easy",   link: LC("valid-parentheses") },
      { id: "sq-8",  title: "Next Greater Element",              difficulty: "Medium", link: LC("next-greater-element-i") },
      { id: "sq-9",  title: "Next Greater Element - 2",          difficulty: "Medium", link: LC("next-greater-element-ii") },
      { id: "sq-10", title: "Asteroid Collision",                difficulty: "Medium", link: LC("asteroid-collision") },
      { id: "sq-11", title: "Sum of Subarray Minimums",          difficulty: "Hard",   link: LC("sum-of-subarray-minimums") },
      { id: "sq-12", title: "Sum of Subarray Ranges",            difficulty: "Hard",   link: LC("sum-of-subarray-ranges") },
      { id: "sq-13", title: "Remove K Digits",                   difficulty: "Medium", link: LC("remove-k-digits") },
      { id: "sq-14", title: "Implement Min Stack",               difficulty: "Medium", link: LC("min-stack") },
      { id: "sq-15", title: "Sliding Window Maximum",            difficulty: "Hard",   link: LC("sliding-window-maximum") },
      { id: "sq-16", title: "Trapping Rainwater",                difficulty: "Hard",   link: LC("trapping-rain-water") },
      { id: "sq-17", title: "Largest Rectangle in a Histogram",  difficulty: "Hard",   link: LC("largest-rectangle-in-histogram") },
      { id: "sq-18", title: "Maximum Rectangles",                difficulty: "Hard",   link: LC("maximal-rectangle") },
      { id: "sq-19", title: "Stock Span Problem",                difficulty: "Medium", link: LC("online-stock-span") },
      { id: "sq-20", title: "Celebrity Problem",                 difficulty: "Medium", link: GFG("the-celebrity-problem") },
      { id: "sq-21", title: "LRU Cache",                         difficulty: "Hard",   link: LC("lru-cache") },
      { id: "sq-22", title: "LFU Cache",                         difficulty: "Hard",   link: LC("lfu-cache") },
    ],
  },
  {
    id: "binary-trees",
    title: "Binary Trees",
    color: "#6d28d9",
    bg: "rgba(109,40,217,0.07)",
    border: "rgba(109,40,217,0.18)",
    problems: [
      { id: "bt-1",  title: "Introduction to Binary Trees",                          difficulty: "Easy",   link: GFG("introduction-to-binary-tree") },
      { id: "bt-2",  title: "Inorder Traversal",                                     difficulty: "Easy",   link: LC("binary-tree-inorder-traversal") },
      { id: "bt-3",  title: "Preorder Traversal",                                    difficulty: "Easy",   link: LC("binary-tree-preorder-traversal") },
      { id: "bt-4",  title: "Postorder Traversal",                                   difficulty: "Easy",   link: LC("binary-tree-postorder-traversal") },
      { id: "bt-5",  title: "Level Order Traversal",                                 difficulty: "Easy",   link: LC("binary-tree-level-order-traversal") },
      { id: "bt-6",  title: "Pre, Post, Inorder in One Traversal",                  difficulty: "Medium", link: GFG("all-traversals-in-binary-tree") },
      { id: "bt-7",  title: "Maximum Depth in BT",                                   difficulty: "Easy",   link: LC("maximum-depth-of-binary-tree") },
      { id: "bt-8",  title: "Check if Two Trees are Identical or Not",               difficulty: "Easy",   link: LC("same-tree") },
      { id: "bt-9",  title: "Check for Balanced Binary Tree",                        difficulty: "Medium", link: LC("balanced-binary-tree") },
      { id: "bt-10", title: "Diameter of Binary Tree",                               difficulty: "Medium", link: LC("diameter-of-binary-tree") },
      { id: "bt-11", title: "Maximum Path Sum",                                      difficulty: "Hard",   link: LC("binary-tree-maximum-path-sum") },
      { id: "bt-12", title: "Check for Symmetrical BTs",                             difficulty: "Easy",   link: LC("symmetric-tree") },
      { id: "bt-13", title: "Zig Zag or Spiral Traversal",                           difficulty: "Medium", link: LC("binary-tree-zigzag-level-order-traversal") },
      { id: "bt-14", title: "Boundary Traversal",                                    difficulty: "Medium", link: GFG("boundary-traversal-of-binary-tree") },
      { id: "bt-15", title: "Vertical Order Traversal",                              difficulty: "Hard",   link: LC("vertical-order-traversal-of-a-binary-tree") },
      { id: "bt-16", title: "Top View of BT",                                        difficulty: "Medium", link: GFG("top-view-of-binary-tree") },
      { id: "bt-17", title: "Bottom View of BT",                                     difficulty: "Medium", link: GFG("bottom-view-of-binary-tree") },
      { id: "bt-18", title: "Right/Left View of BT",                                 difficulty: "Medium", link: LC("binary-tree-right-side-view") },
      { id: "bt-19", title: "Print Root to Node Path in BT",                         difficulty: "Medium", link: GFG("root-to-leaf-paths") },
      { id: "bt-20", title: "LCA in BT",                                             difficulty: "Medium", link: LC("lowest-common-ancestor-of-a-binary-tree") },
      { id: "bt-21", title: "Maximum Width of BT",                                   difficulty: "Medium", link: LC("maximum-width-of-binary-tree") },
      { id: "bt-22", title: "Print All Nodes at a Distance of K in BT",              difficulty: "Medium", link: LC("all-nodes-distance-k-in-binary-tree") },
      { id: "bt-23", title: "Minimum Time Taken to Burn the BT from a Given Node",   difficulty: "Hard",   link: GFG("burning-tree") },
      { id: "bt-24", title: "Count Total Nodes in a Complete BT",                    difficulty: "Medium", link: LC("count-complete-tree-nodes") },
      { id: "bt-25", title: "Requirements Needed to Construct a Unique BT",          difficulty: "Medium", link: GFG("check-whether-the-given-traversals-can-construct-a-binary-tree-or-not") },
      { id: "bt-26", title: "Construct a BT from Preorder and Inorder",              difficulty: "Medium", link: LC("construct-binary-tree-from-preorder-and-inorder-traversal") },
      { id: "bt-27", title: "Construct a BT from Postorder and Inorder",             difficulty: "Medium", link: LC("construct-binary-tree-from-inorder-and-postorder-traversal") },
      { id: "bt-28", title: "Serialize and De-serialize BT",                         difficulty: "Hard",   link: LC("serialize-and-deserialize-binary-tree") },
      { id: "bt-29", title: "Morris Inorder Traversal",                              difficulty: "Medium", link: LC("binary-tree-inorder-traversal") },
      { id: "bt-30", title: "Morris Preorder Traversal",                             difficulty: "Medium", link: LC("binary-tree-preorder-traversal") },
    ],
  },
  {
    id: "bst",
    title: "Binary Search Trees",
    color: "#0f766e",
    bg: "rgba(15,118,110,0.07)",
    border: "rgba(15,118,110,0.18)",
    problems: [
      { id: "bst-1",  title: "Introduction to BST",                           difficulty: "Easy",   link: GFG("binary-search-tree-node-deletion") },
      { id: "bst-2",  title: "Search in BST",                                 difficulty: "Easy",   link: LC("search-in-a-binary-search-tree") },
      { id: "bst-3",  title: "Floor and Ceil in a BST",                       difficulty: "Easy",   link: GFG("floor-in-bst") },
      { id: "bst-4",  title: "Insert a Given Node in BST",                    difficulty: "Easy",   link: LC("insert-into-a-binary-search-tree") },
      { id: "bst-5",  title: "Delete a Node in BST",                          difficulty: "Medium", link: LC("delete-node-in-a-bst") },
      { id: "bst-6",  title: "Kth Smallest and Largest Element in BST",       difficulty: "Medium", link: LC("kth-smallest-element-in-a-bst") },
      { id: "bst-7",  title: "Check if a Tree is a BST or Not",               difficulty: "Medium", link: LC("validate-binary-search-tree") },
      { id: "bst-8",  title: "LCA in BST",                                    difficulty: "Medium", link: LC("lowest-common-ancestor-of-a-binary-search-tree") },
      { id: "bst-9",  title: "Construct a BST from a Preorder Traversal",     difficulty: "Medium", link: LC("construct-binary-search-tree-from-preorder-traversal") },
      { id: "bst-10", title: "Inorder Successor and Predecessor in BST",      difficulty: "Medium", link: GFG("predecessor-and-successor") },
      { id: "bst-11", title: "BST Iterator",                                  difficulty: "Medium", link: LC("binary-search-tree-iterator") },
      { id: "bst-12", title: "Two Sum in BST",                                difficulty: "Medium", link: LC("two-sum-iv-input-is-a-bst") },
      { id: "bst-13", title: "Correct BST with Two Nodes Swapped",            difficulty: "Hard",   link: LC("recover-binary-search-tree") },
      { id: "bst-14", title: "Largest BST in Binary Tree",                    difficulty: "Hard",   link: GFG("largest-bst") },
    ],
  },
  {
    id: "heaps",
    title: "Heaps",
    color: "#7e22ce",
    bg: "rgba(126,34,206,0.07)",
    border: "rgba(126,34,206,0.18)",
    problems: [
      { id: "hp-1",  title: "Heaps Theory",                                          difficulty: "Easy",   link: GFG("heap-sort") },
      { id: "hp-2",  title: "Heapify Algorithm",                                     difficulty: "Easy",   link: GFG("heap-sort") },
      { id: "hp-3",  title: "Build Heap from a Given Array",                         difficulty: "Medium", link: GFG("heap-sort") },
      { id: "hp-4",  title: "Implement Min Heap",                                    difficulty: "Medium", link: GFG("operations-on-binary-min-heap") },
      { id: "hp-5",  title: "Implement Max Heap",                                    difficulty: "Medium", link: GFG("operations-on-binary-max-heap") },
      { id: "hp-6",  title: "Check if an Array Represents a Min Heap",               difficulty: "Easy",   link: GFG("check-if-an-array-represents-a-min-heap") },
      { id: "hp-7",  title: "Convert Min Heap to Max Heap",                          difficulty: "Medium", link: GFG("convert-min-heap-to-max-heap-1666517241") },
      { id: "hp-8",  title: "Heap Sort",                                             difficulty: "Medium", link: GFG("heap-sort") },
      { id: "hp-9",  title: "K-th Largest Element in an Array",                      difficulty: "Medium", link: LC("kth-largest-element-in-an-array") },
      { id: "hp-10", title: "Kth Largest Element in a Stream of Running Integers",   difficulty: "Medium", link: LC("kth-largest-element-in-a-stream") },
    ],
  },
  {
    id: "graphs",
    title: "Graphs",
    color: "#1d4ed8",
    bg: "rgba(29,78,216,0.07)",
    border: "rgba(29,78,216,0.18)",
    problems: [
      { id: "gr2-1",  title: "Introduction to Graph",                               difficulty: "Easy",   link: GFG("introduction-to-graphs") },
      { id: "gr2-2",  title: "Traversal Techniques (BFS/DFS)",                      difficulty: "Easy",   link: GFG("bfs-traversal-of-graph") },
      { id: "gr2-3",  title: "Connected Components",                                difficulty: "Easy",   link: GFG("connected-components-in-an-undirected-graph") },
      { id: "gr2-4",  title: "Number of Provinces",                                 difficulty: "Medium", link: LC("number-of-provinces") },
      { id: "gr2-5",  title: "Number of Islands",                                   difficulty: "Medium", link: LC("number-of-islands") },
      { id: "gr2-6",  title: "Flood Fill Algorithm",                                difficulty: "Easy",   link: LC("flood-fill") },
      { id: "gr2-7",  title: "Number of Enclaves",                                  difficulty: "Medium", link: LC("number-of-enclaves") },
      { id: "gr2-8",  title: "Rotten Oranges",                                      difficulty: "Medium", link: LC("rotting-oranges") },
      { id: "gr2-9",  title: "Distance of Nearest Cell Having One",                 difficulty: "Medium", link: LC("01-matrix") },
      { id: "gr2-10", title: "Surrounded Regions",                                  difficulty: "Medium", link: LC("surrounded-regions") },
      { id: "gr2-11", title: "Number of Distinct Islands",                          difficulty: "Medium", link: GFG("number-of-distinct-islands") },
      { id: "gr2-12", title: "Detect a Cycle in an Undirected Graph",               difficulty: "Medium", link: GFG("detect-cycle-in-an-undirected-graph") },
      { id: "gr2-13", title: "Bipartite Graph",                                     difficulty: "Medium", link: LC("is-graph-bipartite") },
      { id: "gr2-14", title: "Topological Sort / Kahn's Algorithm",                 difficulty: "Medium", link: GFG("topological-sort") },
      { id: "gr2-15", title: "Detect a Cycle in a Directed Graph",                  difficulty: "Medium", link: GFG("detect-cycle-in-a-directed-graph") },
      { id: "gr2-16", title: "Find Eventual Safe States",                           difficulty: "Medium", link: LC("find-eventual-safe-states") },
      { id: "gr2-17", title: "Course Schedule I",                                   difficulty: "Medium", link: LC("course-schedule") },
      { id: "gr2-18", title: "Course Schedule II",                                  difficulty: "Medium", link: LC("course-schedule-ii") },
      { id: "gr2-19", title: "Alien Dictionary",                                    difficulty: "Hard",   link: GFG("alien-dictionary") },
      { id: "gr2-20", title: "Shortest Path in DAG",                                difficulty: "Medium", link: GFG("shortest-path-in-undirected-graph") },
      { id: "gr2-21", title: "Shortest Path in Undirected Graph with Unit Weights", difficulty: "Easy",   link: GFG("shortest-path-in-undirected-graph-having-unit-distance") },
      { id: "gr2-22", title: "Word Ladder I",                                        difficulty: "Hard",   link: LC("word-ladder") },
      { id: "gr2-23", title: "Word Ladder II",                                       difficulty: "Hard",   link: LC("word-ladder-ii") },
      { id: "gr2-24", title: "Dijkstra's Algorithm",                                difficulty: "Medium", link: GFG("implementing-dijkstra-set-1-adjacency-matrix") },
      { id: "gr2-25", title: "Print Shortest Path",                                 difficulty: "Medium", link: GFG("shortest-path-in-weighted-undirected-graph") },
      { id: "gr2-26", title: "Shortest Distance in a Binary Maze",                  difficulty: "Medium", link: LC("shortest-path-in-binary-matrix") },
      { id: "gr2-27", title: "Path with Minimum Effort",                            difficulty: "Medium", link: LC("path-with-minimum-effort") },
      { id: "gr2-28", title: "Cheapest Flight within K Stops",                      difficulty: "Medium", link: LC("cheapest-flights-within-k-stops") },
      { id: "gr2-29", title: "Minimum Multiplications to Reach End",                difficulty: "Medium", link: GFG("minimum-multiplications-to-reach-end") },
      { id: "gr2-30", title: "Number of Ways to Arrive at Destination",             difficulty: "Hard",   link: LC("number-of-ways-to-arrive-at-destination") },
      { id: "gr2-31", title: "Bellman Ford Algorithm",                              difficulty: "Medium", link: GFG("distance-from-the-source-bellman-ford-algorithm") },
      { id: "gr2-32", title: "Floyd Warshall Algorithm",                            difficulty: "Medium", link: GFG("implementing-floyd-warshall2042") },
      { id: "gr2-33", title: "Find the City with Smallest Number of Neighbors",     difficulty: "Medium", link: LC("find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance") },
      { id: "gr2-34", title: "MST Theory",                                          difficulty: "Medium", link: GFG("minimum-spanning-tree") },
      { id: "gr2-35", title: "Disjoint Set (Union-Find)",                           difficulty: "Medium", link: GFG("disjoint-set-union-find") },
      { id: "gr2-36", title: "Find the MST Weight",                                 difficulty: "Medium", link: LC("min-cost-to-connect-all-points") },
      { id: "gr2-37", title: "Number of Operations to Make Network Connected",      difficulty: "Medium", link: LC("number-of-operations-to-make-network-connected") },
      { id: "gr2-38", title: "Accounts Merge",                                      difficulty: "Hard",   link: LC("accounts-merge") },
      { id: "gr2-39", title: "Number of Islands II",                                difficulty: "Hard",   link: GFG("number-of-islands") },
      { id: "gr2-40", title: "Making a Large Island",                               difficulty: "Hard",   link: LC("making-a-large-island") },
      { id: "gr2-41", title: "Most Stones Removed with Same Row or Column",         difficulty: "Hard",   link: LC("most-stones-removed-with-same-row-or-column") },
      { id: "gr2-42", title: "Kosaraju's Algorithm",                                difficulty: "Hard",   link: GFG("strongly-connected-components-kosarajus-algo") },
      { id: "gr2-43", title: "Bridges in Graph",                                    difficulty: "Hard",   link: LC("critical-connections-in-a-network") },
      { id: "gr2-44", title: "Articulation Point in Graph",                         difficulty: "Hard",   link: GFG("articulation-point-1") },
    ],
  },
  {
    id: "dp",
    title: "Dynamic Programming",
    color: "#dc2626",
    bg: "rgba(220,38,38,0.07)",
    border: "rgba(220,38,38,0.18)",
    problems: [
      { id: "dp-1",  title: "Introduction to DP",                                               difficulty: "Easy",   link: GFG("introduction-to-dynamic-programming") },
      { id: "dp-2",  title: "Climbing Stairs",                                                  difficulty: "Easy",   link: LC("climbing-stairs") },
      { id: "dp-3",  title: "Frog Jump",                                                        difficulty: "Easy",   link: GFG("geek-jump") },
      { id: "dp-4",  title: "Frog Jump with K Distances",                                       difficulty: "Medium", link: GFG("minimal-cost") },
      { id: "dp-5",  title: "Maximum Sum of Non Adjacent Elements",                             difficulty: "Medium", link: LC("house-robber") },
      { id: "dp-6",  title: "House Robber",                                                     difficulty: "Medium", link: LC("house-robber") },
      { id: "dp-7",  title: "Ninja's Training",                                                 difficulty: "Medium", link: GFG("ninjas-training") },
      { id: "dp-8",  title: "Grid Unique Paths",                                                difficulty: "Medium", link: LC("unique-paths") },
      { id: "dp-9",  title: "Unique Paths II",                                                  difficulty: "Medium", link: LC("unique-paths-ii") },
      { id: "dp-10", title: "Minimum Falling Path Sum",                                         difficulty: "Medium", link: LC("minimum-falling-path-sum") },
      { id: "dp-11", title: "Triangle",                                                         difficulty: "Medium", link: LC("triangle") },
      { id: "dp-12", title: "Cherry Pickup II",                                                 difficulty: "Hard",   link: LC("cherry-pickup-ii") },
      { id: "dp-13", title: "Best Time to Buy and Sell Stock",                                  difficulty: "Easy",   link: LC("best-time-to-buy-and-sell-stock") },
      { id: "dp-14", title: "Best Time to Buy and Sell Stock II",                               difficulty: "Medium", link: LC("best-time-to-buy-and-sell-stock-ii") },
      { id: "dp-15", title: "Best Time to Buy and Sell Stock III",                              difficulty: "Hard",   link: LC("best-time-to-buy-and-sell-stock-iii") },
      { id: "dp-16", title: "Best Time to Buy and Sell Stock IV",                               difficulty: "Hard",   link: LC("best-time-to-buy-and-sell-stock-iv") },
      { id: "dp-17", title: "Best Time to Buy and Sell Stock with Transaction Fees",            difficulty: "Medium", link: LC("best-time-to-buy-and-sell-stock-with-transaction-fee") },
      { id: "dp-18", title: "Subset Sum Equals to Target",                                      difficulty: "Medium", link: GFG("subset-sum-problem-1611555638") },
      { id: "dp-19", title: "Partition Equal Subset Sum",                                       difficulty: "Medium", link: LC("partition-equal-subset-sum") },
      { id: "dp-20", title: "Partition a Set into Two Subsets with Minimum Absolute Difference", difficulty: "Hard",   link: GFG("minimum-sum-partition3317") },
      { id: "dp-21", title: "Count Subsets with Sum K",                                         difficulty: "Medium", link: GFG("perfect-sum-problem5633") },
      { id: "dp-22", title: "Count Partitions with Given Difference",                           difficulty: "Hard",   link: GFG("partitions-with-given-difference") },
      { id: "dp-23", title: "0 and 1 Knapsack",                                                 difficulty: "Medium", link: GFG("0-1-knapsack-problem0945") },
      { id: "dp-24", title: "Minimum Coins",                                                    difficulty: "Medium", link: LC("coin-change") },
      { id: "dp-25", title: "Target Sum",                                                       difficulty: "Medium", link: LC("target-sum") },
      { id: "dp-26", title: "Coin Change II",                                                   difficulty: "Medium", link: LC("coin-change-ii") },
      { id: "dp-27", title: "Unbounded Knapsack",                                               difficulty: "Medium", link: GFG("unbounded-knapsack-1587115621") },
      { id: "dp-28", title: "Rod Cutting Problem",                                              difficulty: "Medium", link: GFG("rod-cutting0840") },
      { id: "dp-29", title: "Longest Increasing Subsequence",                                   difficulty: "Medium", link: LC("longest-increasing-subsequence") },
      { id: "dp-30", title: "Print Longest Increasing Subsequence",                             difficulty: "Medium", link: GFG("printing-longest-increasing-subsequence") },
      { id: "dp-31", title: "Largest Divisible Subset",                                         difficulty: "Medium", link: LC("largest-divisible-subset") },
      { id: "dp-32", title: "Longest String Chain",                                             difficulty: "Medium", link: LC("longest-string-chain") },
      { id: "dp-33", title: "Longest Bitonic Subsequence",                                      difficulty: "Hard",   link: GFG("longest-bitonic-subsequence0824") },
      { id: "dp-34", title: "Number of Longest Increasing Subsequences",                        difficulty: "Hard",   link: LC("number-of-longest-increasing-subsequences") },
      { id: "dp-35", title: "Longest Common Subsequence",                                       difficulty: "Medium", link: LC("longest-common-subsequence") },
      { id: "dp-36", title: "Longest Common Substring",                                         difficulty: "Medium", link: GFG("longest-common-substring1452") },
      { id: "dp-37", title: "Longest Palindromic Subsequence",                                  difficulty: "Medium", link: LC("longest-palindromic-subsequence") },
      { id: "dp-38", title: "Minimum Insertions to Make String Palindrome",                     difficulty: "Medium", link: LC("minimum-insertion-steps-to-make-a-string-palindrome") },
      { id: "dp-39", title: "Minimum Insertions or Deletions to Convert String A to B",         difficulty: "Medium", link: LC("delete-operation-for-two-strings") },
      { id: "dp-40", title: "Shortest Common Supersequence",                                    difficulty: "Hard",   link: LC("shortest-common-supersequence") },
      { id: "dp-41", title: "Distinct Subsequences",                                            difficulty: "Hard",   link: LC("distinct-subsequences") },
      { id: "dp-42", title: "Edit Distance",                                                    difficulty: "Hard",   link: LC("edit-distance") },
      { id: "dp-43", title: "Wildcard Matching",                                                difficulty: "Hard",   link: LC("wildcard-matching") },
      { id: "dp-44", title: "Matrix Chain Multiplication",                                      difficulty: "Hard",   link: GFG("matrix-chain-multiplication0303") },
      { id: "dp-45", title: "Minimum Cost to Cut the Stick",                                    difficulty: "Hard",   link: LC("minimum-cost-to-cut-a-stick") },
      { id: "dp-46", title: "Burst Balloons",                                                   difficulty: "Hard",   link: LC("burst-balloons") },
      { id: "dp-47", title: "Palindrome Partitioning II",                                       difficulty: "Hard",   link: LC("palindrome-partitioning-ii") },
    ],
  },
  {
    id: "tries",
    title: "Tries",
    color: "#0284c7",
    bg: "rgba(2,132,199,0.07)",
    border: "rgba(2,132,199,0.18)",
    problems: [
      { id: "tr-1", title: "Trie Implementation and Operations",          difficulty: "Medium", link: LC("implement-trie-prefix-tree") },
      { id: "tr-2", title: "Trie Implementation and Advanced Operations", difficulty: "Medium", link: LC("design-add-and-search-words-data-structure") },
      { id: "tr-3", title: "Longest Word with All Prefixes",              difficulty: "Medium", link: LC("longest-word-in-dictionary") },
      { id: "tr-4", title: "Number of Distinct Substrings in a String",   difficulty: "Hard",   link: GFG("number-of-distinct-substrings-in-a-string") },
      { id: "tr-5", title: "Maximum XOR of Two Numbers in an Array",      difficulty: "Hard",   link: LC("maximum-xor-of-two-numbers-in-an-array") },
      { id: "tr-6", title: "Maximum XOR with an Element from an Array",   difficulty: "Hard",   link: LC("maximum-xor-with-an-element-from-array") },
    ],
  },
  {
    id: "strings",
    title: "Strings — Advanced Algorithms",
    color: "#be185d",
    bg: "rgba(190,24,93,0.07)",
    border: "rgba(190,24,93,0.18)",
    problems: [
      { id: "str-1", title: "Reverse Every Word in a String",                                       difficulty: "Easy",   link: LC("reverse-words-in-a-string") },
      { id: "str-2", title: "Minimum Number of Bracket Reversals to Make an Expression Balanced",   difficulty: "Medium", link: GFG("count-the-reversals") },
      { id: "str-3", title: "Count and Say",                                                        difficulty: "Medium", link: LC("count-and-say") },
      { id: "str-4", title: "Rabin Karp Algorithm",                                                 difficulty: "Medium", link: GFG("search-pattern-rabin-karp-algorithm--141631") },
      { id: "str-5", title: "Z Function",                                                           difficulty: "Medium", link: GFG("z-function") },
      { id: "str-6", title: "KMP Algorithm / LPS Array",                                            difficulty: "Hard",   link: LC("find-the-index-of-the-first-occurrence-in-a-string") },
      { id: "str-7", title: "Shortest Palindrome",                                                  difficulty: "Hard",   link: LC("shortest-palindrome") },
      { id: "str-8", title: "Longest Happy Prefix",                                                 difficulty: "Hard",   link: LC("longest-happy-prefix") },
    ],
  },
  {
    id: "maths",
    title: "Maths",
    color: "#65a30d",
    bg: "rgba(101,163,13,0.07)",
    border: "rgba(101,163,13,0.18)",
    problems: [
      { id: "math-1", title: "Print All Primes Till N",              difficulty: "Easy",   link: LC("count-primes") },
      { id: "math-2", title: "Prime Factorisation of a Number",      difficulty: "Easy",   link: GFG("prime-factorization-using-sieve") },
      { id: "math-3", title: "Count Primes in Range L to R",         difficulty: "Medium", link: GFG("count-primes-in-range1604") },
    ],
  },
];

export const TOTAL_PROBLEMS = CODING_TOPICS.reduce((s, t) => s + t.problems.length, 0);
