AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Communication Assessment Backend API

Globals:
  Function:
    Timeout: 60
    MemorySize: 512
    Runtime: python3.12
    Architectures:
      - arm64
    Environment:
      Variables:
        DYNAMODB_TABLE: communication_questions
        INTERVIEW_TABLE: interview_sessions

  Api:
    BinaryMediaTypes:
      - "audio/mpeg"
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Parameters:
  OpenAiApiKey:
    Type: String
    Description: OpenAI API Key
  AzureSpeechKey:
    Type: String
    Description: Azure Speech Key
  AzureSpeechRegion:
    Type: String
    Description: Azure Speech Region

Resources:
  CommunicationAPI:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: communication-assessment-api
      CodeUri: backend/
      Handler: main.handler
      Description: FastAPI backend for Communication Assessment
      Environment:
        Variables:
          DYNAMODB_TABLE: communication_questions
          BEDROCK_REGION: ap-south-1
          OPENAI_API_KEY: !Ref OpenAiApiKey
          AZURE_SPEECH_KEY: !Ref AzureSpeechKey
          AZURE_SPEECH_REGION: !Ref AzureSpeechRegion
          INTERVIEW_TABLE: interview_sessions
          RESUME_BUCKET_NAME: !Ref ResumeBucket
          ALLOWED_ORIGINS: "https://www.harrytheblaze.site,http://localhost:5173,http://localhost:3000"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: communication_questions
        - DynamoDBCrudPolicy:
            TableName: interview_sessions
        - Statement:
          - Effect: Allow
            Action:
              - bedrock:*
              - aws-marketplace:*
              - polly:*
            Resource: '*'
        - S3CrudPolicy:
            BucketName: !Ref ResumeBucket
        - S3ReadPolicy:
            BucketName: !Ref AudioAssetsBucket
      Events:
        ApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        ApiProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY


  CommunicationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: communication_questions
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: section
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: SectionIndex
          KeySchema:
            - AttributeName: section
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  InterviewSessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: interview_sessions
      AttributeDefinitions:
        - AttributeName: session_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: session_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserIdIndex
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  ResumeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "communication-backend-resumebucket-${AWS::StackName}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ["*"]
            AllowedMethods: [PUT, POST, GET]
            AllowedOrigins: ["*"]
            MaxAge: 3000

  AudioAssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ["*"]
            AllowedMethods: [GET]
            AllowedOrigins: ["*"]

  AudioAssetsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AudioAssetsBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${AudioAssetsBucket.Arn}/*"

Outputs:
  CommunicationApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  
  CommunicationApiFunctionArn:
    Description: "Lambda Function ARN"
    Value: !GetAtt CommunicationAPI.Arn

  ResumeBucketName:
    Description: "Name of the S3 bucket for resumes"
    Value: !Ref ResumeBucket

  AudioAssetsBucketName:
    Description: "S3 Bucket for Audio Assets"
    Value: !Ref AudioAssetsBucket
