AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Communication Assessment Backend API

Globals:
  Function:
    Timeout: 60
    MemorySize: 512
    Runtime: python3.12
    Environment:
      Variables:
        DYNAMODB_TABLE: communication_questions

  Api:
    BinaryMediaTypes:
      - "audio/mpeg"
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Parameters:
  AzureSpeechKey:
    Type: String
    Description: Azure Speech Resource Key
  AzureSpeechRegion:
    Type: String
    Description: Azure Speech Resource Region
    Default: eastus
  OpenAiApiKey:
    Type: String
    Description: OpenAI API Key

Resources:
  CommunicationAPI:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: communication-assessment-api
      CodeUri: backend/
      Handler: main.handler
      Description: FastAPI backend for Communication Assessment
      Environment:
        Variables:
          DYNAMODB_TABLE: communication_questions
          BEDROCK_REGION: ap-south-1
          AZURE_SPEECH_KEY: !Ref AzureSpeechKey
          AZURE_SPEECH_REGION: !Ref AzureSpeechRegion
          OPENAI_API_KEY: !Ref OpenAiApiKey
      Policies:
        - DynamoDBCrudPolicy:
            TableName: communication_questions
        - Statement:
          - Effect: Allow
            Action:
              - bedrock:*
              - aws-marketplace:*
            Resource: '*'
      Events:
        ApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        ApiProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY


  CommunicationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: communication_questions
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: section
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: SectionIndex
          KeySchema:
            - AttributeName: section
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

Outputs:
  CommunicationApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  
  CommunicationApiFunctionArn:
    Description: "Lambda Function ARN"
    Value: !GetAtt CommunicationAPI.Arn
